In [ ]:
#scale
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
scale = preprocessing.scale(X_train)
scale

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [ ]:
# StandardScaler
stdscaler= preprocessing.StandardScaler().fit_transform(X_train)
stdscaler

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [ ]:
#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
minmax = MinMaxScaler()
minmax.fit(data)

MinMaxScaler()

In [ ]:
minmax.transform(data)

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [ ]:
minmax.min_ # min - X.min(axis=0) * self.scale_

array([ 0.5  , -0.125])

In [ ]:
minmax.scale_ # (max - min) / (X.max(axis=0) - X.min(axis=0))

array([0.5   , 0.0625])

In [ ]:
minmax.data_min_,minmax.data_max_

(array([-1.,  2.]), array([ 1., 18.]))

In [ ]:
minmax.data_range_  # same as (data_max_ - data_min_)

array([ 2., 16.])

In [ ]:
minmax.n_samples_seen_

4